language: php

php:
  - 7.4

cache:
  files:
    - ./.php_cs.cache

before_script:
  - composer install

script:
  - vendor/bin/psalm --show-info=false
  - vendor/bin/phpunit --coverage-clover ./phpunit.clover

after_script:
  - vendor/bin/php-coveralls -v
