language: php

php:
  - 7.4

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/psalm --show-info=false
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
