language: php

php:
  - 7.4

cache:
  files:
    - ./.php_cs.cache
  directories:
    - $HOME/.composer/cache
    - ./psalm/cache

before_script:
  - composer install

script:
  - vendor/bin/psalm --show-info=false --diff --diff-methods
  - vendor/bin/phpunit --coverage-clover ./phpunit.clover

after_script:
  - vendor/bin/php-coveralls -v
